import random
print()
a=1
while(a):
    s=random.randint(0,6)
    print(s)
    a=int(input("0/1: "))
print()
data=[]
n=int(input(" enter the lenght of the list: "))
for i in range(n):
    b=int(input(" enter the "+str(i+1)+" element into the list: "))
    data.append(b)
print()
print(" the list is",data)
print(" a random element among the list is",random.choice(data))
print()
print(" the random element generated by randrange() is",random.randrange(n))
print()
